refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%F %H:%M:%S%.f)} - {m}{n}"
  main:
    kind: file
    path: "test/actix-web/log/main.log"
    encoder:
      pattern: "{d(%F %H:%M:%S%.f)} - {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  main:
    level: info
    appenders:
      - main
      - stdout
    additive: false
